### ISSUE TITLE
[FR] Use OpenTofu as an alternative to HashiCorp Terraform

### ISSUE THREAD

**Issue by norman-abramovitz** [cloudfoundry/csb-brokerpak-aws#1134]
As OpenTofu and Terraform diverge, it would helpful to support OpenTofu(OpenTF) due to the embedded  nature of Terraform which will violate HashiCorp's BUSL license.

**Comment by pivotal-marcela-campo** [comment]
Hi @norman-abramovitz, thanks for filing this feature request. We are considering our options in the face of the HashiCorp's Licensing changes alongside with other projects of the CNCF and LF. We'll update as soon as we have a strategy in place.

**Comment by kvendingoldo** [comment]
At this moment if you need to have a support of Terraform as well as OpenTofu (and Terragrunt :) ) in one tool you can use https://github.com/tofuutils/tenv which my team wrote some months ago. A lot of users switched to that tool to unify version management in the world of Terraform. 

You're welcome to open any issues or contribute to [tenv](https://github.com/tofuutils/tenv).

**Comment by pivotal-marcela-campo** [comment]
Hi @norman-abramovitz , version 2.0.0 of the broker has moved support from terraform to OpenTofu. There are instructions on how to migrate in the [OpenTofu migration guide](https://github.com/cloudfoundry/cloud-service-broker/blob/main/docs/opentofu_migration_guide.md)
