### ISSUE TITLE
[FR] Support for AWS DocumentDB

### ISSUE THREAD

**Issue by xyloman** [cloudfoundry/csb-brokerpak-aws#2]
**Is your feature request related to a problem? Please describe.**

Ability to manage the lifecycle and credentials used by applications that make use of a DocumentDB instance in AWS.

**Describe the solution you'd like**

Ability to create delete and bind to a Document DB service instance similar to postgres or mysql.

**Describe alternatives you've considered**

Using terraform directly to manage database lifecycle however credential creation on an app by app basis 

**Additional Context**

Teams are branching out and making use of newer data services provided by Amazon and this fits the bill for those that where using MongoDB in the past.

**Priority**

Medium

**Priority Context**

Team is currently developing an application that makes use of this DocumentDB currently and would be looking to roll to production in the Jan/Feb timeframe of 2021.

**Platform** 

AWS

**Applicable Services**

n/a

**Comment by omerbensaadon** [comment]
Hey Bryan, I have flagged this as "good first issue." 

This would be a fantastic opportunity for someone on your team to leverage the [Brokerpak Dissection](https://github.com/cloudfoundry-incubator/cloud-service-broker/blob/master/docs/brokerpak-dissection.md) and get their hands dirty. Contribution would find a welcome home! 

If this is a blocker to your adoption of CSB, please reach out.

**Comment by adampeklay** [comment]
Challenge accepted!

**Comment by pivotal-marcela-campo** [comment]
Hi @adampeklay, if you are looking into contributing to the brokerpak, we have very recently created a [few tutorials](https://github.com/cloudfoundry/cloud-service-broker/tree/main/docs/user-guides) on how to get started. Do not hesitate to reach out either here or at our cloud foundry slack channels [#cloudservicebroker](https://join.slack.com/share/enQtNDA2ODY4NzgxMzQzMC1hMmZlMWFkNWNjOWNiZmRlNWNkZTRmOTNlODkwYWZiYjUwNjEyY2I3MTIxNGFjY2NjNmMyOWEwMmQ0OWJiOTA3?cdn_fallback=1) and [#wg-service-management](https://join.slack.com/share/enQtNDA3NTMwMjAzMzU1NC1iYTFmZDVjZThjMjc5NDZhNGQwNWI2YzJhMWJlZTc1MzYwNzBkMjdkYmRjOTczYThjOTFhOTQ0YTgzY2Q4ZWM3?cdn_fallback=1)

**Comment by aaronclements** [comment]
Two years on, are there any plans on the CloudFoundry side to release an update for this brokerpak that includes DocDB?   I've inherited the above "accepted challenge" on our behalf and it's not proving to be a quick job.  We'd like to avoid any duplicated efforts.  Thanks in advance!  `Aaron @ Smarsh`

**Comment by pivotal-marcela-campo** [comment]
Hi @aaronclements, we have plans to address this in the second part of the year, however we cannot make any promises as priorities might change. You could try to create your own brokerpak or add the service to this brokerpak and contribute it back. For both scenarios I recommend looking into the tutorials mentioned above, specifically the one about [creating your own brokerpak](https://github.com/cloudfoundry/cloud-service-broker/blob/main/docs/user-guides/writing-your-first-brokerpak.md).
We are happy to help and we welcome any feedback that could ease the learning curve to contribute.
