### ISSUE TITLE
Use more specific icon imagery for each specific service type

### ISSUE THREAD

**Issue by alexbarbato** [cloudfoundry/csb-brokerpak-aws#2023]
**Is your feature request related to a problem? Please describe.**
As a user of the CSB tile it is difficult to tell the different offerings apart because they all share the same images.

**Describe the solution you'd like**
Can we use the actual AWS icons for the various services? Is there anything precludes us from doing that?

**Describe alternatives you've considered**
Technically we could probably do any type of icon.

**Additional context**
I'm happy to PR this, but didn't want to do so if we feel there is any legalese that makes the impermissible / maybe it's undesirable for a different reason?

**Comment by zucchinidev** [comment]
Hi @alexbarbato 

We are discussing this matter in a private channel. We are waiting to make a decision.
Thank you for opening the issue.
